#!/bin/bash

set -e

app_name=$(basename $0)

dockash run \
    --as-me \
    --pwd-work \
    --env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin \
    --network host \
    ${app_name} "$@"
