#!/bin/bash

# Set DOCKASH_SOURCE environment variable

# Location of this file.  ref: https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"   

case "${1:-remote}" in
    local)
        export DOCKASH_SOURCE=$SCRIPT_DIR
        echo DOCKASH_SOURCE set to: $DOCKASH_SOURCE
        ;;
    remote)
        unset DOCKASH_SOURCE
        echo DOCKASH_SOURCE unset
        ;;
    *)
        echo $"Usage: $0 {local|remote}"
        exit 1
        ;;
esac


