#!/bin/bash

set -e

app_name=$(basename $0)

dockash run \
    --as-me \
    --pwd-work \
    --mount type=bind,source=$HOME/.gitconfig,target=$HOME/.gitconfig \
    --mount type=bind,source=$HOME/.git-credentials,target=$HOME/.git-credentials \
    ${app_name} "$@"
