#!/bin/bash

set -e

IFS=', ' read -r -a grps <<< "$(id -G $USER)"
add_groups="${grps[*]/#/--group-add }"

app_name=$(basename $0)
entrypoint=${app_name#containerized-}
image=$(dockash image-name $app_name)

config_volumes=()
for d in ${HOME}/{.zoom,.conf}
do
    mkdir -p $d
    config_volumes+=("--mount type=bind,source=$d,target=$d")
done

dockash check-image $app_name
dockash install x11docker

x11docker \
    --pulseaudio \
    --webcam \
    --hostdisplay \
    --gpu \
    --hostdbus \
    --hostipc \
    --cap-default \
    $add_groups \
    --user $(id -u ${USER}):$(id -g ${USER}) \
        -- \
    --rm \
    -it \
    --shm-size=1gb \
    ${config_volumes[@]} \
    --env HOME \
    --env USER \
        -- \
    ${image} \
    ${entrypoint} "$@"

#    --detach \
#    ${entrypoint} "$@"
