#!/bin/bash

set -e

app_name=$(basename $0)
config_volumes=()
for f in .gitconfig .git-credentials
do
    full_path=${HOME}/$f
    [ -f $full_path ] && config_volumes+=("--volume ${full_path}:${full_path}")
done


dockash run \
    --as-me \
    --mount-docker-socket \
    --pwd-work \
    --env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin \
    ${config_volumes[@]} \
    ${app_name} "$@"
