#!/bin/bash

set -e

app_name=$(basename $0)
image=dockash_${USER}_${app_name}:latest
dockerfile_url=https://raw.githubusercontent.com/dan-elias/dockash/master/src/${app_name}/Dockerfile 

if [[ "$(docker images -q ${image} 2> /dev/null)" == "" ]]; then
    curl ${dockerfile_url} | docker build --tag ${image} - 
fi

docker run \
    --rm \
    -i -t  \
    --env HOME \
    --env USER \
    --env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin \
    --user $(id -u ${USER}):$(id -g ${USER}) \
    --volume ${HOME}.gitconfig:${HOME}.gitconfig \
    --volume ${HOME}.git-credentials:${HOME}.git-credentials \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume $(pwd):/work \
    --workdir="/work" \
    ${image} \
    ${app_name} $@
